apiVersion: snorlax.moonbeam.nyc/v1beta1
kind: SleepSchedule
metadata:
  namespace: default
  name: dummy
spec:
  wakeTime: '10:00am'
  sleepTime: '10:01am'
  timezone: 'America/New_York'
  deployments:
  - dummy-frontend
  - dummy-db
  - dummy-redis
  ingresses:
  - dummy-ingress

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-frontend
  template:
    metadata:
      labels:
        app: dummy-frontend
    spec:
      containers:
        - name: dummy
          image: nginx:latest

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-db
  template:
    metadata:
      labels:
        app: dummy-db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dummy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-redis
  template:
    metadata:
      labels:
        app: dummy-redis
    spec:
      containers:
        - name: redis
          image: redis:latest

---

apiVersion: v1
kind: Service
metadata:
  name: dummy-frontend
spec:
  selector:
    app: dummy-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-frontend
                port:
                  number: 80
          - path: /path-one
            pathType: Prefix
            backend:
              service:
                name: dummy-frontend
                port:
                  number: 80
          - path: /path-two
            pathType: Prefix
            backend:
              service:
                name: dummy-frontend
                port:
                  number: 80